/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wly_net_PortScannerActivity */

#ifndef _Included_com_wly_net_PortScannerActivity
#define _Included_com_wly_net_PortScannerActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wly_net_PortScannerActivity
 * Method:    sendPacket
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wly_net_PortScannerActivity_sendPacket
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_PortScannerActivity
 * Method:    computeChecksum
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_com_wly_net_PortScannerActivity_computeChecksum
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
