/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wly_net_IpHeader */

#ifndef _Included_com_wly_net_IpHeader
#define _Included_com_wly_net_IpHeader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wly_net_IpHeader
 * Method:    getIhl
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_wly_net_IpHeader_getIhl
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_IpHeader
 * Method:    getVer
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_wly_net_IpHeader_getVer
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_IpHeader
 * Method:    getTos
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_wly_net_IpHeader_getTos
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_IpHeader
 * Method:    getFlag
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_wly_net_IpHeader_getFlag
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_IpHeader
 * Method:    getTtl
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_wly_net_IpHeader_getTtl
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_IpHeader
 * Method:    getProtocol
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_wly_net_IpHeader_getProtocol
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_IpHeader
 * Method:    getLen
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_wly_net_IpHeader_getLen
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_IpHeader
 * Method:    getIdent
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_wly_net_IpHeader_getIdent
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_IpHeader
 * Method:    getOffset
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_wly_net_IpHeader_getOffset
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_IpHeader
 * Method:    getChksum
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_wly_net_IpHeader_getChksum
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_IpHeader
 * Method:    getSourceIp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_IpHeader_getSourceIp
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_IpHeader
 * Method:    getDestIp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_IpHeader_getDestIp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
