/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wly_net_IpHeader */

#ifndef _Included_com_wly_net_IpHeader
#define _Included_com_wly_net_IpHeader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wly_net_IpHeader
 * Method:    buildIpHeader
 * Signature: (Lcom/wly/net/IpHeader;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wly_net_IpHeader_buildIpHeader
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
