/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wly_net_IpHeader */

#ifndef _Included_com_wly_net_IpHeader
#define _Included_com_wly_net_IpHeader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wly_net_IpHeader
 * Method:    buildIpHeader
 * Signature: (Lcom/wly/net/IpHeader;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wly_net_IpHeader_buildIpHeader
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_wly_net_TcpHeader */

#ifndef _Included_com_wly_net_TcpHeader
#define _Included_com_wly_net_TcpHeader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wly_net_TcpHeader
 * Method:    buildTcpHeader
 * Signature: (Lcom/wly/net/TcpHeader;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wly_net_TcpHeader_buildTcpHeader
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_wly_net_PortScannerActivity */

#ifndef _Included_com_wly_net_PortScannerActivity
#define _Included_com_wly_net_PortScannerActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wly_net_PortScannerActivity
 * Method:    sendPacket
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wly_net_PortScannerActivity_sendPacket
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_PortScannerActivity
 * Method:    computeChecksum
 * Signature: (CI)C
 */
JNIEXPORT jchar JNICALL Java_com_wly_net_PortScannerActivity_computeChecksum
  (JNIEnv *, jobject, jchar, jint);

#ifdef __cplusplus
}
#endif
#endif
