/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wly_net_TcpHeader */

#ifndef _Included_com_wly_net_TcpHeader
#define _Included_com_wly_net_TcpHeader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wly_net_TcpHeader
 * Method:    buildTcpHeader
 * Signature: (Lcom/wly/net/TcpHeader;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wly_net_TcpHeader_buildTcpHeader
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
