/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wly_net_PortScannerActivity */

#ifndef _Included_com_wly_net_PortScannerActivity
#define _Included_com_wly_net_PortScannerActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wly_net_PortScannerActivity
 * Method:    sendPacket
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wly_net_PortScannerActivity_sendPacket
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_PortScannerActivity
 * Method:    computeChecksum
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_wly_net_PortScannerActivity_computeChecksum
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wly_net_PortScannerActivity
 * Method:    buildIpHeader
 * Signature: (Lcom/wly/net/IpHeader;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wly_net_PortScannerActivity_buildIpHeader
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wly_net_PortScannerActivity
 * Method:    buildTcpHeader
 * Signature: (Lcom/wly/net/TcpHeader;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wly_net_PortScannerActivity_buildTcpHeader
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
