/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wly_net_TcpHeader */

#ifndef _Included_com_wly_net_TcpHeader
#define _Included_com_wly_net_TcpHeader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getSourceIp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_TcpHeader_getSourceIp
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getDestIp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_TcpHeader_getDestIp
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getDoff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_TcpHeader_getDoff
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getres1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_TcpHeader_getres1
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getCwr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_TcpHeader_getCwr
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getEce
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_TcpHeader_getEce
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getUrg
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_TcpHeader_getUrg
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getAck
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_TcpHeader_getAck
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getPst
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_TcpHeader_getPst
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getRst
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_TcpHeader_getRst
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getSyn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_TcpHeader_getSyn
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getFin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wly_net_TcpHeader_getFin
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getSeq
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wly_net_TcpHeader_getSeq
  (JNIEnv *, jobject);

/*
 * Class:     com_wly_net_TcpHeader
 * Method:    getAckSeq
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wly_net_TcpHeader_getAckSeq
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
